name = "newssite-worker"
main = "worker/index.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "news-rss-db"
database_id = "2a18b97f-0125-4276-934c-aed5dd0179d2"

[[kv_namespaces]]
binding = "SESSIONS"
id = "2a22c467521f4616a391ae499366f7e0"

[triggers]
crons = ["*/30 * * * *", "0 */2 * * *", "*/5 * * * *", "0 * * * *", "0 */6 * * *"]

[vars]
ENVIRONMENT = "production"
